package:
  name: bayeslite
  version: {{ CONDA_PACKAGE_VERSION }}

source:
  path: ../

build:
  script: python setup.py install

requirements:
  build:
    - cython >=0.20.1
    - git
    - python 2.7.*
    - jsonschema
    - numpy 1.8.*
  run:
    - cgpm
    - crosscat
    - jsonschema
    - numpy 1.8.*
    - scipy >=0.13,<=0.19
    - six 1.10.*

test:
  requires:
    - apsw
    - cgpm
    - crosscat
    - pandas >=0.14,<0.19
    - pytest 2.5.1.*
    - python 2.7.*
  commands:
    - python -m pytest --pyargs bayeslite -k "not __ci_"

about:
  home: https://github.com/probcomp/bayeslite
  license: Apache
  license_file: LICENSE.txt
