package:
  name: bayeslite
  version: {{ CONDA_PACKAGE_VERSION }}

source:
  path: ../

build:
  script: python setup.py install

requirements:
  build:
    - cython 0.23.*
    - git
    - jsonschema
    - numpy 1.11.*
    - python 2.7.*
  run:
    - apsw
    - cgpm
    - crosscat
    - jsonschema
    - loom 0.2.10
    - numpy 1.11.*
    - protobuf
    - scipy 0.17.*
    - six 1.10.*

test:
  requires:
    - apsw
    - cgpm
    - contextlib2 >=0.4.0
    - crosscat
    - loom 0.2.10
    - pandas 0.18.*
    - parsable 0.2.*
    - protobuf
    - pytest 2.8.*
    - python 2.7.*
  commands:
    - python -m pytest --pyargs bayeslite -k "not __ci_"

about:
  home: https://github.com/probcomp/bayeslite
  license: Apache
  license_file: LICENSE.txt
