package:
  name: bayeslite
  version: {{ CONDA_PACKAGE_VERSION }}

source:
  path: ../

build:
  script: python setup.py install

requirements:
  build:
    - cython 0.23.*
    - git
    - python 2.7.*
    - jsonschema
    - numpy 1.11.*
  run:
    - cgpm
    - crosscat
    - jsonschema
    - numpy 1.11.0
    - scipy 0.17.0
    - six 1.10.*

test:
  requires:
    - apsw
    - cgpm
    - crosscat
    - pandas 0.17.1
    - pytest 2.8.7
    - python 2.7.*
  commands:
    - python -m pytest --pyargs bayeslite -k "not __ci_"

about:
  home: https://github.com/probcomp/bayeslite
  license: Apache
  license_file: LICENSE.txt
